worlds:
- world
biomes:
  D: DESERT
  J: JUNGLE
  T: TAIGA
  O: OCEAN
grid size: 3
map:
- ODJDO
- DDJTD
- JJTDJ
- DTDJD
- ODJDO
outer wall: minecraft:barrier
inner wall lower: minecraft:bedrock
inner wall higher: minecraft:glass
inner wall gap: 15